import{a as v,S as w,i as S}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=a(t);fetch(t.href,n)}})();const q="53511640-00e42e73f696871d7dee14b6b",P="https://pixabay.com/api/";async function y(e,r=1,a=15){try{const{data:o}=await v.get(P,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}});return o}catch(o){throw console.error("Помилка при отриманні зображень:",o.message),o}}const m=document.querySelector(".gallery"),x=document.querySelector(".loader"),M=document.querySelector(".loading-text"),$=new w(".gallery a",{captionsData:"alt",captionDelay:250});function g(e){const r=e.map(B).join("");m.insertAdjacentHTML("beforeend",r),$.refresh()}function O(){m.innerHTML=""}function p(){L(!0)}function b(){L(!1)}function B({webformatURL:e,largeImageURL:r,tags:a,likes:o,views:t,comments:n,downloads:c}){return`
    <li class="gallery-item">
      <a href="${r}">
        <img src="${e}" alt="${a}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${t}</p>
        <p><b>Comments:</b> ${n}</p>
        <p><b>Downloads:</b> ${c}</p>
      </div>
    </li>
  `}function L(e){x.classList.toggle("visible",e),M.classList.toggle("visible",e)}const C=document.querySelector("#search-form"),h=document.querySelector("#load-more");let u="",s=1,d=0;const l=15;C.addEventListener("submit",E);h.addEventListener("click",H);async function E(e){e.preventDefault();const r=e.target.elements["search-text"].value.trim();if(!r)return i("warning","Увага","Поле пошуку не може бути порожнім!","#ffc107");u=r,s=1,O(),f(),p();try{const{hits:a,totalHits:o}=await y(u,s,l);if(d=o,!a.length)return i("info","Немає результатів","Sorry, there are no images matching your search query. Please try again!","#ff4d4d","#fff");g(a),a.length<l||s*l>=d?(f(),i("info","Кінець колекції","We're sorry, but you've reached the end of search results.","#17a2b8","#fff")):A()}catch{i("error","Помилка","Не вдалося завантажити зображення.","#ff4d4d","#fff")}finally{b()}}async function H(){s+=1,p();try{const{hits:e}=await y(u,s,l);if(!e.length)return f(),i("info","Кінець колекції","We're sorry, but you've reached the end of search results.","#17a2b8","#fff");g(e),T(),s*l>=d&&(f(),i("info","Кінець колекції","We're sorry, but you've reached the end of search results.","#17a2b8","#fff"))}catch{i("error","Помилка","Не вдалося завантажити додаткові зображення.","#ff4d4d","#fff")}finally{b()}}function T(){const e=document.querySelector(".gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}function i(e,r,a,o,t="#000"){S[e]({title:r,message:a,position:"topRight",backgroundColor:o,titleColor:t,messageColor:t,maxWidth:400,timeout:3e3})}function A(){h.classList.remove("hidden")}function f(){h.classList.add("hidden")}
//# sourceMappingURL=index.js.map
